RikaApp/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Mvc;

namespace RikaApp.Controllers
{
    public class CategoriesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

RikaApp/Controllers/MyCartController.cs
using Microsoft.AspNetCore.Mvc;

namespace RikaApp.Controllers
{
    public class MyCartController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

RikaApp/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Mvc;

namespace RikaApp.Controllers
{
    public class OrdersController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

RikaApp/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;

namespace RikaApp.Controllers
{
    public class ProfileController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

RikaApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="sv-se">
<head>
    <meta charset="utf-8">
    <meta name="veiwport" content="width=device-width, initial-scale=1.0">

    <script src="https://kit.fontawesome.com/a5c95d093e.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    <link rel="icon" href="~/favicon.ico" type="image/png">

    <title>@ViewData["Title"] - Rika</title>

</head>
<body>
    <div class="wrapper">
        
        <header>
            <a class="menu-link" asp-controller="Home" asp-action="Index">Home</a>
            <a class="menu-link" asp-controller="Products" asp-action="Index">Products</a>
            <a class="menu-link" asp-controller="Categories" asp-action="Index">Categories</a>
            <a class="menu-link" asp-controller="MyCart" asp-action="Index">My Cart</a>
            <a class="menu-link" asp-controller="Orders" asp-action="Index">My Orders</a>
            <a class="menu-link" asp-controller="Profile" asp-action="Index">My Profile</a>
            
        </header>

        <main>
            @RenderBody()

        </main>
        
        <footer>
            <a class="menu-link" asp-controller="AdminProductPortal" asp-action="Index">Admin Products Portal</a>
        </footer>

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="~/js/site.js"></script>

</body>

</html>

RikaApp/Views/Shared/_ValidationScriptPartial.cshtml
<script src="~/js/validation.js"></script>